#ifndef scripting_engine_hpp_INCLUDED
#define scripting_engine_hpp_INCLUDED
#include <chrono>
#include <cstdint>
#include <string>
#include <sstream>
#include <filesystem>
#include <optional>
#include <span>
#include <vector>
// Contains Scanner, Parser and then interpretation

// Scanner

namespace rmf::scripting {

enum class e_ErrorTypes: uint8_t {
    LexicalError,
    SyntaxError,
    RuntimeError,
};


enum class e_TokenType: uint8_t {
    Symbol, // All filtering mechanisms are functions by default.

    // Literal values
    NumLit, // 001235, 0b1010101, 0xfF12, 0o6712
    StrLit, // "hellow", """multilines"""
    FltLit, // 0.12345678
    DurationLit,

    Dot,
    Comma,

    Plus,
    Times,
    Divide,
    Minus,

    Assignment,
    OpenParen, // ()
    CloseParen,
    OpenBracket, // []
    CloseBracket,
    OpenBrace, // {}
    CloseBrace,

    // Keywords
    Delete, // We can manually control the scope.
    Sleep,
    For,
    If,
    In,
    End,

    SemiColon,
    Colon, // Used for generating ranges.
    Eof,
};

using TokenValue = std::variant<std::monostate, std::string, long long, double, std::chrono::nanoseconds>;

struct Token {
    e_TokenType type;
    TokenValue value;
};

// Takes in bare strings of each line, keeps track of everything and
// converts them into tokens for the parser.
class Scanner {
private:
    // hold the state of the scanner as well, ensure correct syntax (but not grammar).
    std::vector<Token> m_tokens;
    std::stringstream m_fileContents;
    // Will throw an error if parsing failes
    Token parseNextToken();
    void skipSpaces();

    Token parseSymbolOrKeyword(char curChar);
    Token parseNumber(char curChar);
    Token parseStringLiteral(char curChar);

public:
    // Will load the entire file into memory and then close it.
    Scanner(const std::filesystem::path &filename);

    // Begins parsing the entire file.
    void parseFile();

    // Returns a span of the tokens.
    const std::span<Token> getTokensSpan();
    const std::vector<Token> getTokens();
};

// Takes in the tokens from the scanner and generates a AST
// which then can be run by the scripting engine.
class Parser {
private:
    // Parser state.

public:
    Parser(const std::span<Token> &tokens);
};

// Takes in the ASTs generated by the parser and then runs them.
// Also has all the state and what not.
class Runner {};

// Provides simplified APIs for the combination of the 4 above classes.
class ScriptingEngine {};

} // namespace rmf::scripting


#endif // scripting_engine_hpp_INCLUDED
